baseURL = "/"
languageCode = "en-us"
title = "Home"
themesDir = "themes"
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"


[taxonomies]
  category = 'categories'
  tag = 'tags'


[params]
  google_analytics_id = ""
  twitter_handle = "@kevinYENG"

  showAuthorOnHomepage = true
  showAuthorOnPosts = true
  showPostsOnHomepage = false

  addFrame = true
  addDot = true
  dotColor = "#004d40"

  highlightColor = '#004d40'
  baseColor = ''
  baseOffsetColor = ''
  textColor = ''
  headingColor = ''

